#!/bin/sh
#
# Print the host's MAC address
#
# Syntax:
#
#     mac-address
#
# Example:
#
#     $ mac-address
#     721ab4c5287a
#
# A media access control address (MAC address) of a computer 
# is a unique identifier assigned to network interfaces for 
# communications at the data link layer of a network segment.
#
# https://en.wikipedia.org/wiki/MAC_address
#
# ## Implementation
#
# This script is intended to run on any Unix-like system.
#
# This script runs the command `ifconfig`, finds any occurances
# of `ether` (typical macOS) or `HWaddre` (typical Linux),
# and prints the matches. 
#
# Many typical systems can have more than one MAC address.
# For example, a system can have a MAC address for the wired
# interface and a different MAC address for a WiFi interface.
# This script intentially prints the first matching MAC address.
#
# We have tested it on a typical MacBook macOS 10.12-10.15 system
# and a typical Ubuntu Linux 16.04 system.
#
# ## Tracking
#
# * Command: mac-address
# * Version: 1.2.0
# * Created: 2016-10-01
# * Updated: 2020-02-25
# * License: GPL
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
ifconfig -a | grep  -m1 "^[[:space:]]\+\(HWaddr\|ether\)[[:space:]]" | sed 's/ *$//; s/.* //;  s/[[:space:]]\+$//; s/://g'
